name: matrix workflow
on:
    push:
        branches:
           - main
jobs:
    Installing-Software:
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest]
        runs-on: ubuntu-22.04
        steps:
           - name: Checkout the code
             uses: actions/checkout@v3
           - name: Setup Node.js environment
             uses: actions/setup-node@v4.0.3
             with:
                node-version: 20
           - name: Install dependencies
             run: npm ci
           - name: Build Project
             run: npm run build

          
